### ISSUE TITLE
[Feature]: Compatibility with backslot and map atlas or an alternative slot placement for the charm of undying

### ISSUE THREAD

**Issue by ManeBOI** [illusivesoulworks/charmofundying#37]
### What is the new feature or improvement?

(talking about the fabric version btw)the slots sometimes interfere with each other

**Comment by TheIllusiveC4** [comment]
Charm of Undying uses Trinkets API for its slot, which in turn is used by many other mods. If there's slot interference, it's up to the mods like Back Slot and Map Atlas to make sure their slot is compatible.
